import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";

/**
 * Threat model: promotion approval proves the request came from the Electron main process that
 * owns the managed daemon. The 32-byte HMAC key below is generated by Electron main and reaches
 * the daemon only over the authenticated, non-reopenable bootstrap pipe (see
 * scripts/daemon-bootstrap.ts), so authenticated protocol clients (TUI, arbitrary socket clients)
 * cannot forge an approval. The daemon holding the symmetric key in memory is acceptable because
 * arbitrary same-user native malware is explicitly out of scope — see the "Promotion is enabled
 * only when Electron acquires the daemon startup lock" paragraph in README.md.
 */

export interface PromotionApprovalRequest {
  readonly missionId: string;
  readonly planRevisionId: string;
  readonly changeRevision: string;
  readonly decision: "accepted" | "rejected";
  readonly contentDigest: string;
}

export interface VerifiedPromotionApproval { readonly nonce: string; readonly expiresAt: string; readonly reviewerId: string }
export interface PromotionApprovalVerifier { verify(input: PromotionApprovalRequest & { readonly capability: string }): VerifiedPromotionApproval }
export interface PromotionApprovalIssuer { issue(input: PromotionApprovalRequest): string }
export interface TrustedApprovalContext { readonly now?: () => string; readonly id?: () => string; readonly maximumTtlMs?: number; readonly approvalKey?: string }

interface SealedApproval extends PromotionApprovalRequest { readonly issuedAt: string; readonly expiresAt: string; readonly nonce: string }
const FIELDS = ["missionId", "planRevisionId", "changeRevision", "decision", "contentDigest", "issuedAt", "expiresAt", "nonce"];
const ID = /^[A-Za-z0-9_-]{1,128}$/;
const DIGEST = /^[0-9a-f]{64}$/;
const KEY_BYTES = 32;

export class TrustedApprovalService implements PromotionApprovalIssuer {
  readonly approvalKey: string;
  private readonly key: Buffer;
  private readonly now: () => string;
  private readonly id: () => string;
  private readonly maximumTtlMs: number;

  constructor(context: TrustedApprovalContext = {}) {
    this.now = context.now ?? (() => new Date().toISOString());
    this.id = context.id ?? (() => crypto.randomUUID());
    this.maximumTtlMs = context.maximumTtlMs ?? 60_000;
    if (!Number.isSafeInteger(this.maximumTtlMs) || this.maximumTtlMs <= 0) throw new Error("Promotion approval maximum TTL must be positive.");
    this.key = context.approvalKey ? decodeApprovalKey(context.approvalKey) : randomBytes(KEY_BYTES);
    this.approvalKey = this.key.toString("base64url");
  }

  issue(input: PromotionApprovalRequest): string {
    validateRequest(input);
    const issuedAt = this.now();
    const payload: SealedApproval = { ...input, issuedAt, expiresAt: new Date(Date.parse(issuedAt) + this.maximumTtlMs).toISOString(), nonce: this.id() };
    const encoded = Buffer.from(JSON.stringify(payload)).toString("base64url");
    return `${encoded}.${seal(this.key, encoded)}`;
  }
}

export class PinnedApprovalVerifier implements PromotionApprovalVerifier {
  private readonly key: Buffer;
  private readonly reviewerId: string;
  private readonly now: () => string;
  private readonly maximumTtlMs: number;
  private readonly maximumClockSkewMs: number;

  constructor(approvalKey: string, options: { now?: () => string; maximumTtlMs?: number; maximumClockSkewMs?: number } = {}) {
    this.key = decodeApprovalKey(approvalKey);
    this.reviewerId = approvalPrincipal(approvalKey);
    this.now = options.now ?? (() => new Date().toISOString());
    this.maximumTtlMs = options.maximumTtlMs ?? 60_000;
    this.maximumClockSkewMs = options.maximumClockSkewMs ?? 5_000;
  }

  verify(input: PromotionApprovalRequest & { readonly capability: string }): VerifiedPromotionApproval {
    validateRequest(input);
    const [encoded, tag, extra] = input.capability.split(".");
    if (!encoded || !tag || extra || !sealed(this.key, encoded, tag)) throw new Error("Promotion approval capability is invalid.");
    let payload: unknown;
    try { payload = JSON.parse(Buffer.from(encoded, "base64url").toString("utf8")); } catch { throw new Error("Promotion approval schema is invalid."); }
    assertPayload(payload);
    if (payload.missionId !== input.missionId || payload.planRevisionId !== input.planRevisionId || payload.changeRevision !== input.changeRevision || payload.decision !== input.decision || payload.contentDigest !== input.contentDigest) throw new Error("Promotion approval does not match the request.");
    const now = Date.parse(this.now());
    const issuedAt = Date.parse(payload.issuedAt);
    const expiresAt = Date.parse(payload.expiresAt);
    if (issuedAt > now + this.maximumClockSkewMs) throw new Error("Promotion approval clock is invalid.");
    if (expiresAt - issuedAt > this.maximumTtlMs) throw new Error("Promotion approval lifetime exceeds the maximum.");
    if (expiresAt <= now) throw new Error("Promotion approval expired.");
    return { nonce: payload.nonce, expiresAt: payload.expiresAt, reviewerId: this.reviewerId };
  }
}

export function approvalPrincipal(approvalKey: string): string {
  return `electron-${approvalKeyFingerprint(approvalKey).slice(0, 32)}`;
}
export function approvalKeyFingerprint(approvalKey: string): string {
  return createHash("sha256").update(decodeApprovalKey(approvalKey)).digest("hex");
}

function seal(key: Buffer, encoded: string): string {
  return createHmac("sha256", key).update(encoded, "utf8").digest("base64url");
}
function sealed(key: Buffer, encoded: string, tag: string): boolean {
  const expected = Buffer.from(seal(key, encoded), "utf8");
  const presented = Buffer.from(tag, "utf8");
  return expected.length === presented.length && timingSafeEqual(expected, presented);
}
function decodeApprovalKey(approvalKey: string): Buffer {
  const key = Buffer.from(approvalKey, "base64url");
  if (key.length !== KEY_BYTES) throw new Error("Promotion approval key must be 32 bytes, base64url encoded.");
  return key;
}

function validateRequest(value: PromotionApprovalRequest): void {
  if (!ID.test(value.missionId) || !ID.test(value.planRevisionId) || !ID.test(value.changeRevision) || !DIGEST.test(value.contentDigest) || (value.decision !== "accepted" && value.decision !== "rejected")) throw new Error("Promotion approval request is invalid.");
}

function assertPayload(value: unknown): asserts value is SealedApproval {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Promotion approval schema is invalid.");
  const item = value as Record<string, unknown>;
  if (Object.keys(item).length !== FIELDS.length || !FIELDS.every((field) => Object.hasOwn(item, field)) || !ID.test(String(item.missionId)) || !ID.test(String(item.planRevisionId)) || !ID.test(String(item.changeRevision)) || !ID.test(String(item.nonce)) || !DIGEST.test(String(item.contentDigest)) || (item.decision !== "accepted" && item.decision !== "rejected") || !isTimestamp(item.issuedAt) || !isTimestamp(item.expiresAt)) throw new Error("Promotion approval schema is invalid.");
}

function isTimestamp(value: unknown): value is string { return typeof value === "string" && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value; }
